name: Release Workflow

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install project dependencies
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Update Code Coverage
        run: yarn cov:send

      - name: Update docs
        run: yarn doc:html

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build/docs -u "github-actions-bot <support+actions@github.com>" -m "[ci skip] Updates"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build
        run: yarn build

      - name: Clean up for publishing
        run: |
          rm -rf .github .nyc_output .vscode coverage build/docs examples node_modules src
          rm -f .editorconfig .eslintrc.json .gitignore .prettierignore tsconfig.json tsconfig.module.json yarn.lock
          rm -f -- build/**/*.tsbuildinfo build/**/*.spec.d.ts build/**/*.spec.js

      - name: Publish Package to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
